server:
    port: 8080
    servlet:
        context-path: /api

spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:h2:mem:monorepo
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true
                dialect: org.hibernate.dialect.H2Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
    devtools:
        restart:
            enabled: true

# SpringDoc OpenAPI Configuration
springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
    show-actuator: false

logging:
    level:
        "[org.springframework.web]": INFO
        "[com.example.backend]": DEBUG
